language: ruby
script: "bundle exec rake appraisal:integration test"
rvm:
  - 2.0.0
env:
  - INTEGRATION=default
  - INTEGRATION=active_model
  - INTEGRATION=active_record
notifications:
  disabled: true
matrix:
